[package]
authors = ["Mark Schmale <m.schmale@uniorg.de>"]
name = "raytracer"
version = "0.1.0"

[dependencies]
assert_approx_eq = "1.0.0"
cgmath = "0.15.0"
image = "0.15.0"
num_cpus = "1.6.2"
threadpool = "1.5.0"
wavefront_obj = "5.1.0"
